// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.organization-invitation-worker@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const ORGANIZATION_INVITATION_WORKER_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const ORGANIZATION_INVITATION_WORKER_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_organization_invitation_worker { () => { "{\"capability_id\":\"lenso.organization-invitation-worker@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"dispatch_due\",\"expire_due\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_organization_invitation_worker_client { () => { "{\"capability_id\":\"lenso.organization-invitation-worker@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_organization_invitation_worker_client { () => { "{\"capability_id\":\"lenso.organization-invitation-worker@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const DISPATCH_DUE_OPERATION: &str = "dispatch_due";
pub const EXPIRE_DUE_OPERATION: &str = "expire_due";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DispatchDueRequest {
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DispatchDueResponse {
    #[serde(rename = "completed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed: i64,
    #[serde(rename = "has_more")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub has_more: bool,
    #[serde(rename = "permanent_failed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub permanent_failed: i64,
    #[serde(rename = "processed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub processed: i64,
    #[serde(rename = "retry_scheduled")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub retry_scheduled: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DispatchDueError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExpireDueRequest {
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExpireDueResponse {
    #[serde(rename = "expired")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expired: i64,
    #[serde(rename = "has_more")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub has_more: bool,
    #[serde(rename = "items")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub items: Vec<ExpireDueResponseItemsItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExpireDueResponseItemsItem {
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "invitation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub invitation_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ExpireDueError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct OrganizationInvitationWorkerDispatchDue;
impl RequestCapability for OrganizationInvitationWorkerDispatchDue {
    type Request = DispatchDueRequest;
    type Response = DispatchDueResponse;
    type DomainError = DispatchDueError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DISPATCH_DUE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationInvitationWorkerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).dispatch_due(context, request)
    }
}

#[derive(Debug)]
pub struct OrganizationInvitationWorkerExpireDue;
impl RequestCapability for OrganizationInvitationWorkerExpireDue {
    type Request = ExpireDueRequest;
    type Response = ExpireDueResponse;
    type DomainError = ExpireDueError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != EXPIRE_DUE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationInvitationWorkerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).expire_due(context, request)
    }
}

impl serde::Serialize for DispatchDueError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DispatchDueError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ExpireDueError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ExpireDueError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_dispatch_due_request(value: &DispatchDueRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_dispatch_due_request(wire: &str) -> Result<DispatchDueRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_dispatch_due_response(value: &DispatchDueResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_dispatch_due_response(wire: &str) -> Result<DispatchDueResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_dispatch_due_error(value: &DispatchDueError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_dispatch_due_error(wire: &str) -> Result<DispatchDueError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_expire_due_request(value: &ExpireDueRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_expire_due_request(wire: &str) -> Result<ExpireDueRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_expire_due_response(value: &ExpireDueResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_expire_due_response(wire: &str) -> Result<ExpireDueResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_expire_due_error(value: &ExpireDueError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_expire_due_error(wire: &str) -> Result<ExpireDueError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoOrganizationInvitationWorkerDispatchDueResult {
    fn __lenso_into_result(self) -> Result<Result<DispatchDueResponse, DispatchDueError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationInvitationWorkerDispatchDueResult for Result<DispatchDueResponse, DispatchDueError> {
    fn __lenso_into_result(self) -> Result<Result<DispatchDueResponse, DispatchDueError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationInvitationWorkerDispatchDueResult for Result<Result<DispatchDueResponse, DispatchDueError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DispatchDueResponse, DispatchDueError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationInvitationWorkerDispatchDueResult for Result<DispatchDueResponse, lenso_plugin_authoring::PluginError<DispatchDueError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DispatchDueResponse, DispatchDueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationInvitationWorkerDispatchDueResult for Result<DispatchDueResponse, OrganizationInvitationWorkerDispatchDueInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DispatchDueResponse, DispatchDueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationInvitationWorkerDispatchDueInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationInvitationWorkerDispatchDueInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOrganizationInvitationWorkerExpireDueResult {
    fn __lenso_into_result(self) -> Result<Result<ExpireDueResponse, ExpireDueError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationInvitationWorkerExpireDueResult for Result<ExpireDueResponse, ExpireDueError> {
    fn __lenso_into_result(self) -> Result<Result<ExpireDueResponse, ExpireDueError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationInvitationWorkerExpireDueResult for Result<Result<ExpireDueResponse, ExpireDueError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ExpireDueResponse, ExpireDueError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationInvitationWorkerExpireDueResult for Result<ExpireDueResponse, lenso_plugin_authoring::PluginError<ExpireDueError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ExpireDueResponse, ExpireDueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationInvitationWorkerExpireDueResult for Result<ExpireDueResponse, OrganizationInvitationWorkerExpireDueInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ExpireDueResponse, ExpireDueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationInvitationWorkerExpireDueInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationInvitationWorkerExpireDueInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait OrganizationInvitationWorkerProvider: fmt::Debug + 'static {
    fn dispatch_due(&self, context: InvocationContext, request: DispatchDueRequest) -> NativeRequestFuture<OrganizationInvitationWorkerDispatchDue>;
    fn expire_due(&self, context: InvocationContext, request: ExpireDueRequest) -> NativeRequestFuture<OrganizationInvitationWorkerExpireDue>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_organization_invitation_worker {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOrganizationInvitationWorker;
        impl $crate::OrganizationInvitationWorkerProvider for $plugin {
        fn dispatch_due(&self, context: __LensoNativeSupportOrganizationInvitationWorker::InvocationContext, request: $crate::DispatchDueRequest) -> __LensoNativeSupportOrganizationInvitationWorker::NativeRequestFuture<$crate::OrganizationInvitationWorkerDispatchDue> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::dispatch_due(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationInvitationWorkerDispatchDueResult::__lenso_into_result(result)
            })
        }
        fn expire_due(&self, context: __LensoNativeSupportOrganizationInvitationWorker::InvocationContext, request: $crate::ExpireDueRequest) -> __LensoNativeSupportOrganizationInvitationWorker::NativeRequestFuture<$crate::OrganizationInvitationWorkerExpireDue> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::expire_due(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationInvitationWorkerExpireDueResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct OrganizationInvitationWorkerRequestEndpoint { provider: Rc<dyn OrganizationInvitationWorkerProvider> }

#[derive(Debug)]
pub struct OrganizationInvitationWorkerEndpoint<P: OrganizationInvitationWorkerProvider> { provider: Rc<P>, request_endpoint: OrganizationInvitationWorkerRequestEndpoint }
impl<P: OrganizationInvitationWorkerProvider> OrganizationInvitationWorkerEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn OrganizationInvitationWorkerProvider> = provider.clone();
        Self { provider, request_endpoint: OrganizationInvitationWorkerRequestEndpoint { provider: request_provider } }
    }
}

impl<P: OrganizationInvitationWorkerProvider> NativeRequestEndpoint for OrganizationInvitationWorkerEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        DISPATCH_DUE_OPERATION,
        EXPIRE_DUE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            DISPATCH_DUE_OPERATION => {
                let Ok(request) = request.downcast::<DispatchDueRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).dispatch_due(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            EXPIRE_DUE_OPERATION => {
                let Ok(request) = request.downcast::<ExpireDueRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).expire_due(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_organization_invitation_worker {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::OrganizationInvitationWorkerEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_organization_invitation_worker {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_organization_invitation_worker!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct OrganizationInvitationWorkerClient {
    dispatch_due: NativeRequestHandle<OrganizationInvitationWorkerDispatchDue>,
    expire_due: NativeRequestHandle<OrganizationInvitationWorkerExpireDue>,
}
impl OrganizationInvitationWorkerClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn dispatch_due(&self, request: DispatchDueRequest) -> Result<DispatchDueResponse, OrganizationInvitationWorkerDispatchDueInvocationError> {
        self.dispatch_due.invoke(DISPATCH_DUE_OPERATION, request).await
            .map_err(OrganizationInvitationWorkerDispatchDueInvocationError::Runtime)?
            .map_err(OrganizationInvitationWorkerDispatchDueInvocationError::Domain)
    }

    pub async fn dispatch_due_with_context(&self, context: InvocationContext, request: DispatchDueRequest) -> Result<DispatchDueResponse, OrganizationInvitationWorkerDispatchDueInvocationError> {
        self.dispatch_due.invoke_with_context(DISPATCH_DUE_OPERATION, context, request).await
            .map_err(OrganizationInvitationWorkerDispatchDueInvocationError::Runtime)?
            .map_err(OrganizationInvitationWorkerDispatchDueInvocationError::Domain)
    }

    pub async fn expire_due(&self, request: ExpireDueRequest) -> Result<ExpireDueResponse, OrganizationInvitationWorkerExpireDueInvocationError> {
        self.expire_due.invoke(EXPIRE_DUE_OPERATION, request).await
            .map_err(OrganizationInvitationWorkerExpireDueInvocationError::Runtime)?
            .map_err(OrganizationInvitationWorkerExpireDueInvocationError::Domain)
    }

    pub async fn expire_due_with_context(&self, context: InvocationContext, request: ExpireDueRequest) -> Result<ExpireDueResponse, OrganizationInvitationWorkerExpireDueInvocationError> {
        self.expire_due.invoke_with_context(EXPIRE_DUE_OPERATION, context, request).await
            .map_err(OrganizationInvitationWorkerExpireDueInvocationError::Runtime)?
            .map_err(OrganizationInvitationWorkerExpireDueInvocationError::Domain)
    }
}

impl CapabilityClient for OrganizationInvitationWorkerClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            dispatch_due: dependencies.one::<OrganizationInvitationWorkerDispatchDue>()?,
            expire_due: dependencies.one::<OrganizationInvitationWorkerExpireDue>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for OrganizationInvitationWorkerClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    dispatch_due: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationInvitationWorkerDispatchDue>()?,
                    expire_due: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationInvitationWorkerExpireDue>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationInvitationWorkerDispatchDueInvocationError {
    Domain(DispatchDueError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationInvitationWorkerExpireDueInvocationError {
    Domain(ExpireDueError),
    Runtime(RuntimeFailure),
}
