// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.organization-invitation@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const ORGANIZATION_INVITATION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const ORGANIZATION_INVITATION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_organization_invitation { () => { "{\"capability_id\":\"lenso.organization-invitation@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"accept\",\"get_invitation\",\"invite\",\"list_invitations\",\"resend\",\"revoke\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_organization_invitation_client { () => { "{\"capability_id\":\"lenso.organization-invitation@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_organization_invitation_client { () => { "{\"capability_id\":\"lenso.organization-invitation@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const ACCEPT_OPERATION: &str = "accept";
pub const GET_INVITATION_OPERATION: &str = "get_invitation";
pub const INVITE_OPERATION: &str = "invite";
pub const LIST_INVITATIONS_OPERATION: &str = "list_invitations";
pub const RESEND_OPERATION: &str = "resend";
pub const REVOKE_OPERATION: &str = "revoke";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AcceptRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "invitation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub invitation_id: String,
    #[serde(rename = "token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub token: String,
}

impl fmt::Debug for AcceptRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AcceptRequest")
            .field("expected_revision", &self.expected_revision)
            .field("idempotency_key", &self.idempotency_key)
            .field("invitation_id", &self.invitation_id)
            .field("token", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AcceptResponse {
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "invitation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub invitation_id: String,
    #[serde(rename = "membership_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub membership_id: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: AcceptResponseState,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum AcceptResponseState {
    #[serde(rename = "accepted")]
    Accepted,
}

#[derive(Clone, Debug, PartialEq)]
pub enum AcceptError {
    AcceptanceInProgress,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    InvitationExpired,
    InvitationNotFound,
    RevisionConflict,
    TokenInvalid,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetInvitationRequest {
    #[serde(rename = "invitation_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub invitation_ref: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetInvitationResponse {
    #[serde(rename = "acceptance_pending")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub acceptance_pending: bool,
    #[serde(rename = "accepted_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted_at: Option<Timestamp>,
    #[serde(rename = "accepted_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted_subject: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "delivery_state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_state: GetInvitationResponseDeliveryState,
    #[serde(rename = "email")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub email: String,
    #[serde(rename = "expired_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expired_at: Option<Timestamp>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "invitation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub invitation_id: String,
    #[serde(rename = "inviter_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub inviter_subject: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "revoked_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked_at: Option<Timestamp>,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: GetInvitationResponseState,
    #[serde(rename = "token_expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub token_expires_at: Timestamp,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

impl fmt::Debug for GetInvitationResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("GetInvitationResponse")
            .field("acceptance_pending", &self.acceptance_pending)
            .field("accepted_at", &self.accepted_at)
            .field("accepted_subject", &self.accepted_subject)
            .field("created_at", &self.created_at)
            .field("delivery_state", &self.delivery_state)
            .field("email", &"<redacted>")
            .field("expired_at", &self.expired_at)
            .field("identifier", &self.identifier)
            .field("invitation_id", &self.invitation_id)
            .field("inviter_subject", &self.inviter_subject)
            .field("organization_id", &self.organization_id)
            .field("revision", &self.revision)
            .field("revoked_at", &self.revoked_at)
            .field("state", &self.state)
            .field("token_expires_at", &self.token_expires_at)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetInvitationResponseDeliveryState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "superseded")]
    Superseded,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetInvitationResponseState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetInvitationError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    InvitationExists,
    InvitationNotFound,
    OrganizationInactive,
    OrganizationNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InviteRequest {
    #[serde(rename = "email")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub email: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

impl fmt::Debug for InviteRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("InviteRequest")
            .field("email", &"<redacted>")
            .field("idempotency_key", &self.idempotency_key)
            .field("organization_id", &self.organization_id)
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InviteResponse {
    #[serde(rename = "acceptance_pending")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub acceptance_pending: bool,
    #[serde(rename = "accepted_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted_at: Option<Timestamp>,
    #[serde(rename = "accepted_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted_subject: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "delivery_state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_state: InviteResponseDeliveryState,
    #[serde(rename = "email")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub email: String,
    #[serde(rename = "expired_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expired_at: Option<Timestamp>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "invitation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub invitation_id: String,
    #[serde(rename = "invitation_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub invitation_token: Option<String>,
    #[serde(rename = "inviter_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub inviter_subject: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "revoked_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked_at: Option<Timestamp>,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: InviteResponseState,
    #[serde(rename = "token_expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub token_expires_at: Timestamp,
    #[serde(rename = "token_returned")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub token_returned: bool,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

impl fmt::Debug for InviteResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("InviteResponse")
            .field("acceptance_pending", &self.acceptance_pending)
            .field("accepted_at", &self.accepted_at)
            .field("accepted_subject", &self.accepted_subject)
            .field("created_at", &self.created_at)
            .field("delivery_state", &self.delivery_state)
            .field("email", &"<redacted>")
            .field("expired_at", &self.expired_at)
            .field("identifier", &self.identifier)
            .field("invitation_id", &self.invitation_id)
            .field("invitation_token", &"<redacted>")
            .field("inviter_subject", &self.inviter_subject)
            .field("organization_id", &self.organization_id)
            .field("revision", &self.revision)
            .field("revoked_at", &self.revoked_at)
            .field("state", &self.state)
            .field("token_expires_at", &self.token_expires_at)
            .field("token_returned", &self.token_returned)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum InviteResponseDeliveryState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "superseded")]
    Superseded,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum InviteResponseState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum InviteError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    InvitationExists,
    InvitationNotFound,
    OrganizationInactive,
    OrganizationNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListInvitationsRequest {
    #[serde(rename = "cursor")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(rename = "email")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "state")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<ListInvitationsRequestState>,
}

impl fmt::Debug for ListInvitationsRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ListInvitationsRequest")
            .field("cursor", &self.cursor)
            .field("email", &"<redacted>")
            .field("limit", &self.limit)
            .field("organization_id", &self.organization_id)
            .field("state", &self.state)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListInvitationsRequestState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListInvitationsResponse {
    #[serde(rename = "items")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub items: Vec<ListInvitationsResponseItemsItem>,
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListInvitationsResponseItemsItem {
    #[serde(rename = "acceptance_pending")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub acceptance_pending: bool,
    #[serde(rename = "accepted_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted_at: Option<Timestamp>,
    #[serde(rename = "accepted_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted_subject: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "delivery_state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_state: ListInvitationsResponseItemsItemDeliveryState,
    #[serde(rename = "email")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub email: String,
    #[serde(rename = "expired_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expired_at: Option<Timestamp>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "invitation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub invitation_id: String,
    #[serde(rename = "inviter_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub inviter_subject: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "revoked_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked_at: Option<Timestamp>,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: ListInvitationsResponseItemsItemState,
    #[serde(rename = "token_expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub token_expires_at: Timestamp,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

impl fmt::Debug for ListInvitationsResponseItemsItem {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ListInvitationsResponseItemsItem")
            .field("acceptance_pending", &self.acceptance_pending)
            .field("accepted_at", &self.accepted_at)
            .field("accepted_subject", &self.accepted_subject)
            .field("created_at", &self.created_at)
            .field("delivery_state", &self.delivery_state)
            .field("email", &"<redacted>")
            .field("expired_at", &self.expired_at)
            .field("identifier", &self.identifier)
            .field("invitation_id", &self.invitation_id)
            .field("inviter_subject", &self.inviter_subject)
            .field("organization_id", &self.organization_id)
            .field("revision", &self.revision)
            .field("revoked_at", &self.revoked_at)
            .field("state", &self.state)
            .field("token_expires_at", &self.token_expires_at)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListInvitationsResponseItemsItemDeliveryState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "superseded")]
    Superseded,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListInvitationsResponseItemsItemState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListInvitationsError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    InvitationExists,
    InvitationNotFound,
    OrganizationInactive,
    OrganizationNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResendRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "invitation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub invitation_id: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResendResponse {
    #[serde(rename = "acceptance_pending")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub acceptance_pending: bool,
    #[serde(rename = "accepted_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted_at: Option<Timestamp>,
    #[serde(rename = "accepted_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted_subject: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "delivery_state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_state: ResendResponseDeliveryState,
    #[serde(rename = "email")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub email: String,
    #[serde(rename = "expired_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expired_at: Option<Timestamp>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "invitation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub invitation_id: String,
    #[serde(rename = "invitation_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub invitation_token: Option<String>,
    #[serde(rename = "inviter_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub inviter_subject: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "revoked_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked_at: Option<Timestamp>,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: ResendResponseState,
    #[serde(rename = "token_expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub token_expires_at: Timestamp,
    #[serde(rename = "token_returned")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub token_returned: bool,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

impl fmt::Debug for ResendResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ResendResponse")
            .field("acceptance_pending", &self.acceptance_pending)
            .field("accepted_at", &self.accepted_at)
            .field("accepted_subject", &self.accepted_subject)
            .field("created_at", &self.created_at)
            .field("delivery_state", &self.delivery_state)
            .field("email", &"<redacted>")
            .field("expired_at", &self.expired_at)
            .field("identifier", &self.identifier)
            .field("invitation_id", &self.invitation_id)
            .field("invitation_token", &"<redacted>")
            .field("inviter_subject", &self.inviter_subject)
            .field("organization_id", &self.organization_id)
            .field("revision", &self.revision)
            .field("revoked_at", &self.revoked_at)
            .field("state", &self.state)
            .field("token_expires_at", &self.token_expires_at)
            .field("token_returned", &self.token_returned)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ResendResponseDeliveryState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "superseded")]
    Superseded,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ResendResponseState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ResendError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    InvitationExists,
    InvitationNotFound,
    OrganizationInactive,
    OrganizationNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "invitation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub invitation_id: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeResponse {
    #[serde(rename = "acceptance_pending")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub acceptance_pending: bool,
    #[serde(rename = "accepted_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted_at: Option<Timestamp>,
    #[serde(rename = "accepted_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted_subject: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "delivery_state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_state: RevokeResponseDeliveryState,
    #[serde(rename = "email")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub email: String,
    #[serde(rename = "expired_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expired_at: Option<Timestamp>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "invitation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub invitation_id: String,
    #[serde(rename = "inviter_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub inviter_subject: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "revoked_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revoked_at: Option<Timestamp>,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: RevokeResponseState,
    #[serde(rename = "token_expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub token_expires_at: Timestamp,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

impl fmt::Debug for RevokeResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("RevokeResponse")
            .field("acceptance_pending", &self.acceptance_pending)
            .field("accepted_at", &self.accepted_at)
            .field("accepted_subject", &self.accepted_subject)
            .field("created_at", &self.created_at)
            .field("delivery_state", &self.delivery_state)
            .field("email", &"<redacted>")
            .field("expired_at", &self.expired_at)
            .field("identifier", &self.identifier)
            .field("invitation_id", &self.invitation_id)
            .field("inviter_subject", &self.inviter_subject)
            .field("organization_id", &self.organization_id)
            .field("revision", &self.revision)
            .field("revoked_at", &self.revoked_at)
            .field("state", &self.state)
            .field("token_expires_at", &self.token_expires_at)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RevokeResponseDeliveryState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "superseded")]
    Superseded,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RevokeResponseState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RevokeError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    InvitationExists,
    InvitationNotFound,
    OrganizationInactive,
    OrganizationNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct OrganizationInvitationAccept;
impl RequestCapability for OrganizationInvitationAccept {
    type Request = AcceptRequest;
    type Response = AcceptResponse;
    type DomainError = AcceptError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ACCEPT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationInvitationRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).accept(context, request)
    }
}

#[derive(Debug)]
pub struct OrganizationInvitationGetInvitation;
impl RequestCapability for OrganizationInvitationGetInvitation {
    type Request = GetInvitationRequest;
    type Response = GetInvitationResponse;
    type DomainError = GetInvitationError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_INVITATION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationInvitationRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_invitation(context, request)
    }
}

#[derive(Debug)]
pub struct OrganizationInvitationInvite;
impl RequestCapability for OrganizationInvitationInvite {
    type Request = InviteRequest;
    type Response = InviteResponse;
    type DomainError = InviteError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != INVITE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationInvitationRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).invite(context, request)
    }
}

#[derive(Debug)]
pub struct OrganizationInvitationListInvitations;
impl RequestCapability for OrganizationInvitationListInvitations {
    type Request = ListInvitationsRequest;
    type Response = ListInvitationsResponse;
    type DomainError = ListInvitationsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_INVITATIONS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationInvitationRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_invitations(context, request)
    }
}

#[derive(Debug)]
pub struct OrganizationInvitationResend;
impl RequestCapability for OrganizationInvitationResend {
    type Request = ResendRequest;
    type Response = ResendResponse;
    type DomainError = ResendError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RESEND_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationInvitationRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).resend(context, request)
    }
}

#[derive(Debug)]
pub struct OrganizationInvitationRevoke;
impl RequestCapability for OrganizationInvitationRevoke {
    type Request = RevokeRequest;
    type Response = RevokeResponse;
    type DomainError = RevokeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REVOKE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationInvitationRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).revoke(context, request)
    }
}

impl serde::Serialize for AcceptError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AcceptanceInProgress => serializer.serialize_str("acceptance_in_progress"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::InvitationExpired => serializer.serialize_str("invitation_expired"),
            Self::InvitationNotFound => serializer.serialize_str("invitation_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::TokenInvalid => serializer.serialize_str("token_invalid"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for AcceptError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "acceptance_in_progress" => Ok(Self::AcceptanceInProgress),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "invitation_expired" => Ok(Self::InvitationExpired),
                "invitation_not_found" => Ok(Self::InvitationNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "token_invalid" => Ok(Self::TokenInvalid),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for GetInvitationError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::InvitationExists => serializer.serialize_str("invitation_exists"),
            Self::InvitationNotFound => serializer.serialize_str("invitation_not_found"),
            Self::OrganizationInactive => serializer.serialize_str("organization_inactive"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetInvitationError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "invitation_exists" => Ok(Self::InvitationExists),
                "invitation_not_found" => Ok(Self::InvitationNotFound),
                "organization_inactive" => Ok(Self::OrganizationInactive),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for InviteError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::InvitationExists => serializer.serialize_str("invitation_exists"),
            Self::InvitationNotFound => serializer.serialize_str("invitation_not_found"),
            Self::OrganizationInactive => serializer.serialize_str("organization_inactive"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for InviteError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "invitation_exists" => Ok(Self::InvitationExists),
                "invitation_not_found" => Ok(Self::InvitationNotFound),
                "organization_inactive" => Ok(Self::OrganizationInactive),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListInvitationsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::InvitationExists => serializer.serialize_str("invitation_exists"),
            Self::InvitationNotFound => serializer.serialize_str("invitation_not_found"),
            Self::OrganizationInactive => serializer.serialize_str("organization_inactive"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListInvitationsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "invitation_exists" => Ok(Self::InvitationExists),
                "invitation_not_found" => Ok(Self::InvitationNotFound),
                "organization_inactive" => Ok(Self::OrganizationInactive),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ResendError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::InvitationExists => serializer.serialize_str("invitation_exists"),
            Self::InvitationNotFound => serializer.serialize_str("invitation_not_found"),
            Self::OrganizationInactive => serializer.serialize_str("organization_inactive"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ResendError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "invitation_exists" => Ok(Self::InvitationExists),
                "invitation_not_found" => Ok(Self::InvitationNotFound),
                "organization_inactive" => Ok(Self::OrganizationInactive),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RevokeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::InvitationExists => serializer.serialize_str("invitation_exists"),
            Self::InvitationNotFound => serializer.serialize_str("invitation_not_found"),
            Self::OrganizationInactive => serializer.serialize_str("organization_inactive"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RevokeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "invitation_exists" => Ok(Self::InvitationExists),
                "invitation_not_found" => Ok(Self::InvitationNotFound),
                "organization_inactive" => Ok(Self::OrganizationInactive),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_accept_request(value: &AcceptRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_accept_request(wire: &str) -> Result<AcceptRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_accept_response(value: &AcceptResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_accept_response(wire: &str) -> Result<AcceptResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_accept_error(value: &AcceptError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_accept_error(wire: &str) -> Result<AcceptError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_get_invitation_request(value: &GetInvitationRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_invitation_request(wire: &str) -> Result<GetInvitationRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_invitation_response(value: &GetInvitationResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_invitation_response(wire: &str) -> Result<GetInvitationResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_invitation_error(value: &GetInvitationError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_invitation_error(wire: &str) -> Result<GetInvitationError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_invite_request(value: &InviteRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_invite_request(wire: &str) -> Result<InviteRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_invite_response(value: &InviteResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_invite_response(wire: &str) -> Result<InviteResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_invite_error(value: &InviteError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_invite_error(wire: &str) -> Result<InviteError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_invitations_request(value: &ListInvitationsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_invitations_request(wire: &str) -> Result<ListInvitationsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_invitations_response(value: &ListInvitationsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_invitations_response(wire: &str) -> Result<ListInvitationsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_invitations_error(value: &ListInvitationsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_invitations_error(wire: &str) -> Result<ListInvitationsError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_resend_request(value: &ResendRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resend_request(wire: &str) -> Result<ResendRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_resend_response(value: &ResendResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resend_response(wire: &str) -> Result<ResendResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_resend_error(value: &ResendError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resend_error(wire: &str) -> Result<ResendError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_revoke_request(value: &RevokeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_request(wire: &str) -> Result<RevokeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_response(value: &RevokeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_response(wire: &str) -> Result<RevokeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_error(value: &RevokeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_error(wire: &str) -> Result<RevokeError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoOrganizationInvitationAcceptResult {
    fn __lenso_into_result(self) -> Result<Result<AcceptResponse, AcceptError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationInvitationAcceptResult for Result<AcceptResponse, AcceptError> {
    fn __lenso_into_result(self) -> Result<Result<AcceptResponse, AcceptError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationInvitationAcceptResult for Result<Result<AcceptResponse, AcceptError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<AcceptResponse, AcceptError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationInvitationAcceptResult for Result<AcceptResponse, lenso_plugin_authoring::PluginError<AcceptError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<AcceptResponse, AcceptError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationInvitationAcceptResult for Result<AcceptResponse, OrganizationInvitationAcceptInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<AcceptResponse, AcceptError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationInvitationAcceptInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationInvitationAcceptInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOrganizationInvitationGetInvitationResult {
    fn __lenso_into_result(self) -> Result<Result<GetInvitationResponse, GetInvitationError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationInvitationGetInvitationResult for Result<GetInvitationResponse, GetInvitationError> {
    fn __lenso_into_result(self) -> Result<Result<GetInvitationResponse, GetInvitationError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationInvitationGetInvitationResult for Result<Result<GetInvitationResponse, GetInvitationError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetInvitationResponse, GetInvitationError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationInvitationGetInvitationResult for Result<GetInvitationResponse, lenso_plugin_authoring::PluginError<GetInvitationError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetInvitationResponse, GetInvitationError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationInvitationGetInvitationResult for Result<GetInvitationResponse, OrganizationInvitationGetInvitationInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetInvitationResponse, GetInvitationError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationInvitationGetInvitationInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationInvitationGetInvitationInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOrganizationInvitationInviteResult {
    fn __lenso_into_result(self) -> Result<Result<InviteResponse, InviteError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationInvitationInviteResult for Result<InviteResponse, InviteError> {
    fn __lenso_into_result(self) -> Result<Result<InviteResponse, InviteError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationInvitationInviteResult for Result<Result<InviteResponse, InviteError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<InviteResponse, InviteError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationInvitationInviteResult for Result<InviteResponse, lenso_plugin_authoring::PluginError<InviteError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<InviteResponse, InviteError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationInvitationInviteResult for Result<InviteResponse, OrganizationInvitationInviteInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<InviteResponse, InviteError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationInvitationInviteInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationInvitationInviteInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOrganizationInvitationListInvitationsResult {
    fn __lenso_into_result(self) -> Result<Result<ListInvitationsResponse, ListInvitationsError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationInvitationListInvitationsResult for Result<ListInvitationsResponse, ListInvitationsError> {
    fn __lenso_into_result(self) -> Result<Result<ListInvitationsResponse, ListInvitationsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationInvitationListInvitationsResult for Result<Result<ListInvitationsResponse, ListInvitationsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListInvitationsResponse, ListInvitationsError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationInvitationListInvitationsResult for Result<ListInvitationsResponse, lenso_plugin_authoring::PluginError<ListInvitationsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListInvitationsResponse, ListInvitationsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationInvitationListInvitationsResult for Result<ListInvitationsResponse, OrganizationInvitationListInvitationsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListInvitationsResponse, ListInvitationsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationInvitationListInvitationsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationInvitationListInvitationsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOrganizationInvitationResendResult {
    fn __lenso_into_result(self) -> Result<Result<ResendResponse, ResendError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationInvitationResendResult for Result<ResendResponse, ResendError> {
    fn __lenso_into_result(self) -> Result<Result<ResendResponse, ResendError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationInvitationResendResult for Result<Result<ResendResponse, ResendError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ResendResponse, ResendError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationInvitationResendResult for Result<ResendResponse, lenso_plugin_authoring::PluginError<ResendError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ResendResponse, ResendError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationInvitationResendResult for Result<ResendResponse, OrganizationInvitationResendInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ResendResponse, ResendError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationInvitationResendInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationInvitationResendInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOrganizationInvitationRevokeResult {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationInvitationRevokeResult for Result<RevokeResponse, RevokeError> {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationInvitationRevokeResult for Result<Result<RevokeResponse, RevokeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationInvitationRevokeResult for Result<RevokeResponse, lenso_plugin_authoring::PluginError<RevokeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationInvitationRevokeResult for Result<RevokeResponse, OrganizationInvitationRevokeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationInvitationRevokeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationInvitationRevokeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait OrganizationInvitationProvider: fmt::Debug + 'static {
    fn accept(&self, context: InvocationContext, request: AcceptRequest) -> NativeRequestFuture<OrganizationInvitationAccept>;
    fn get_invitation(&self, context: InvocationContext, request: GetInvitationRequest) -> NativeRequestFuture<OrganizationInvitationGetInvitation>;
    fn invite(&self, context: InvocationContext, request: InviteRequest) -> NativeRequestFuture<OrganizationInvitationInvite>;
    fn list_invitations(&self, context: InvocationContext, request: ListInvitationsRequest) -> NativeRequestFuture<OrganizationInvitationListInvitations>;
    fn resend(&self, context: InvocationContext, request: ResendRequest) -> NativeRequestFuture<OrganizationInvitationResend>;
    fn revoke(&self, context: InvocationContext, request: RevokeRequest) -> NativeRequestFuture<OrganizationInvitationRevoke>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_organization_invitation {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOrganizationInvitation;
        impl $crate::OrganizationInvitationProvider for $plugin {
        fn accept(&self, context: __LensoNativeSupportOrganizationInvitation::InvocationContext, request: $crate::AcceptRequest) -> __LensoNativeSupportOrganizationInvitation::NativeRequestFuture<$crate::OrganizationInvitationAccept> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::accept(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationInvitationAcceptResult::__lenso_into_result(result)
            })
        }
        fn get_invitation(&self, context: __LensoNativeSupportOrganizationInvitation::InvocationContext, request: $crate::GetInvitationRequest) -> __LensoNativeSupportOrganizationInvitation::NativeRequestFuture<$crate::OrganizationInvitationGetInvitation> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_invitation(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationInvitationGetInvitationResult::__lenso_into_result(result)
            })
        }
        fn invite(&self, context: __LensoNativeSupportOrganizationInvitation::InvocationContext, request: $crate::InviteRequest) -> __LensoNativeSupportOrganizationInvitation::NativeRequestFuture<$crate::OrganizationInvitationInvite> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::invite(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationInvitationInviteResult::__lenso_into_result(result)
            })
        }
        fn list_invitations(&self, context: __LensoNativeSupportOrganizationInvitation::InvocationContext, request: $crate::ListInvitationsRequest) -> __LensoNativeSupportOrganizationInvitation::NativeRequestFuture<$crate::OrganizationInvitationListInvitations> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_invitations(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationInvitationListInvitationsResult::__lenso_into_result(result)
            })
        }
        fn resend(&self, context: __LensoNativeSupportOrganizationInvitation::InvocationContext, request: $crate::ResendRequest) -> __LensoNativeSupportOrganizationInvitation::NativeRequestFuture<$crate::OrganizationInvitationResend> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::resend(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationInvitationResendResult::__lenso_into_result(result)
            })
        }
        fn revoke(&self, context: __LensoNativeSupportOrganizationInvitation::InvocationContext, request: $crate::RevokeRequest) -> __LensoNativeSupportOrganizationInvitation::NativeRequestFuture<$crate::OrganizationInvitationRevoke> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::revoke(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationInvitationRevokeResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct OrganizationInvitationRequestEndpoint { provider: Rc<dyn OrganizationInvitationProvider> }

#[derive(Debug)]
pub struct OrganizationInvitationEndpoint<P: OrganizationInvitationProvider> { provider: Rc<P>, request_endpoint: OrganizationInvitationRequestEndpoint }
impl<P: OrganizationInvitationProvider> OrganizationInvitationEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn OrganizationInvitationProvider> = provider.clone();
        Self { provider, request_endpoint: OrganizationInvitationRequestEndpoint { provider: request_provider } }
    }
}

impl<P: OrganizationInvitationProvider> NativeRequestEndpoint for OrganizationInvitationEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        ACCEPT_OPERATION,
        GET_INVITATION_OPERATION,
        INVITE_OPERATION,
        LIST_INVITATIONS_OPERATION,
        RESEND_OPERATION,
        REVOKE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            ACCEPT_OPERATION => {
                let Ok(request) = request.downcast::<AcceptRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).accept(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            GET_INVITATION_OPERATION => {
                let Ok(request) = request.downcast::<GetInvitationRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_invitation(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            INVITE_OPERATION => {
                let Ok(request) = request.downcast::<InviteRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).invite(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_INVITATIONS_OPERATION => {
                let Ok(request) = request.downcast::<ListInvitationsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_invitations(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RESEND_OPERATION => {
                let Ok(request) = request.downcast::<ResendRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).resend(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REVOKE_OPERATION => {
                let Ok(request) = request.downcast::<RevokeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).revoke(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_organization_invitation {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::OrganizationInvitationEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_organization_invitation {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_organization_invitation!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct OrganizationInvitationClient {
    accept: NativeRequestHandle<OrganizationInvitationAccept>,
    get_invitation: NativeRequestHandle<OrganizationInvitationGetInvitation>,
    invite: NativeRequestHandle<OrganizationInvitationInvite>,
    list_invitations: NativeRequestHandle<OrganizationInvitationListInvitations>,
    resend: NativeRequestHandle<OrganizationInvitationResend>,
    revoke: NativeRequestHandle<OrganizationInvitationRevoke>,
}
impl OrganizationInvitationClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn accept(&self, request: AcceptRequest) -> Result<AcceptResponse, OrganizationInvitationAcceptInvocationError> {
        self.accept.invoke(ACCEPT_OPERATION, request).await
            .map_err(OrganizationInvitationAcceptInvocationError::Runtime)?
            .map_err(OrganizationInvitationAcceptInvocationError::Domain)
    }

    pub async fn accept_with_context(&self, context: InvocationContext, request: AcceptRequest) -> Result<AcceptResponse, OrganizationInvitationAcceptInvocationError> {
        self.accept.invoke_with_context(ACCEPT_OPERATION, context, request).await
            .map_err(OrganizationInvitationAcceptInvocationError::Runtime)?
            .map_err(OrganizationInvitationAcceptInvocationError::Domain)
    }

    pub async fn get_invitation(&self, request: GetInvitationRequest) -> Result<GetInvitationResponse, OrganizationInvitationGetInvitationInvocationError> {
        self.get_invitation.invoke(GET_INVITATION_OPERATION, request).await
            .map_err(OrganizationInvitationGetInvitationInvocationError::Runtime)?
            .map_err(OrganizationInvitationGetInvitationInvocationError::Domain)
    }

    pub async fn get_invitation_with_context(&self, context: InvocationContext, request: GetInvitationRequest) -> Result<GetInvitationResponse, OrganizationInvitationGetInvitationInvocationError> {
        self.get_invitation.invoke_with_context(GET_INVITATION_OPERATION, context, request).await
            .map_err(OrganizationInvitationGetInvitationInvocationError::Runtime)?
            .map_err(OrganizationInvitationGetInvitationInvocationError::Domain)
    }

    pub async fn invite(&self, request: InviteRequest) -> Result<InviteResponse, OrganizationInvitationInviteInvocationError> {
        self.invite.invoke(INVITE_OPERATION, request).await
            .map_err(OrganizationInvitationInviteInvocationError::Runtime)?
            .map_err(OrganizationInvitationInviteInvocationError::Domain)
    }

    pub async fn invite_with_context(&self, context: InvocationContext, request: InviteRequest) -> Result<InviteResponse, OrganizationInvitationInviteInvocationError> {
        self.invite.invoke_with_context(INVITE_OPERATION, context, request).await
            .map_err(OrganizationInvitationInviteInvocationError::Runtime)?
            .map_err(OrganizationInvitationInviteInvocationError::Domain)
    }

    pub async fn list_invitations(&self, request: ListInvitationsRequest) -> Result<ListInvitationsResponse, OrganizationInvitationListInvitationsInvocationError> {
        self.list_invitations.invoke(LIST_INVITATIONS_OPERATION, request).await
            .map_err(OrganizationInvitationListInvitationsInvocationError::Runtime)?
            .map_err(OrganizationInvitationListInvitationsInvocationError::Domain)
    }

    pub async fn list_invitations_with_context(&self, context: InvocationContext, request: ListInvitationsRequest) -> Result<ListInvitationsResponse, OrganizationInvitationListInvitationsInvocationError> {
        self.list_invitations.invoke_with_context(LIST_INVITATIONS_OPERATION, context, request).await
            .map_err(OrganizationInvitationListInvitationsInvocationError::Runtime)?
            .map_err(OrganizationInvitationListInvitationsInvocationError::Domain)
    }

    pub async fn resend(&self, request: ResendRequest) -> Result<ResendResponse, OrganizationInvitationResendInvocationError> {
        self.resend.invoke(RESEND_OPERATION, request).await
            .map_err(OrganizationInvitationResendInvocationError::Runtime)?
            .map_err(OrganizationInvitationResendInvocationError::Domain)
    }

    pub async fn resend_with_context(&self, context: InvocationContext, request: ResendRequest) -> Result<ResendResponse, OrganizationInvitationResendInvocationError> {
        self.resend.invoke_with_context(RESEND_OPERATION, context, request).await
            .map_err(OrganizationInvitationResendInvocationError::Runtime)?
            .map_err(OrganizationInvitationResendInvocationError::Domain)
    }

    pub async fn revoke(&self, request: RevokeRequest) -> Result<RevokeResponse, OrganizationInvitationRevokeInvocationError> {
        self.revoke.invoke(REVOKE_OPERATION, request).await
            .map_err(OrganizationInvitationRevokeInvocationError::Runtime)?
            .map_err(OrganizationInvitationRevokeInvocationError::Domain)
    }

    pub async fn revoke_with_context(&self, context: InvocationContext, request: RevokeRequest) -> Result<RevokeResponse, OrganizationInvitationRevokeInvocationError> {
        self.revoke.invoke_with_context(REVOKE_OPERATION, context, request).await
            .map_err(OrganizationInvitationRevokeInvocationError::Runtime)?
            .map_err(OrganizationInvitationRevokeInvocationError::Domain)
    }
}

impl CapabilityClient for OrganizationInvitationClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            accept: dependencies.one::<OrganizationInvitationAccept>()?,
            get_invitation: dependencies.one::<OrganizationInvitationGetInvitation>()?,
            invite: dependencies.one::<OrganizationInvitationInvite>()?,
            list_invitations: dependencies.one::<OrganizationInvitationListInvitations>()?,
            resend: dependencies.one::<OrganizationInvitationResend>()?,
            revoke: dependencies.one::<OrganizationInvitationRevoke>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for OrganizationInvitationClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    accept: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationInvitationAccept>()?,
                    get_invitation: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationInvitationGetInvitation>()?,
                    invite: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationInvitationInvite>()?,
                    list_invitations: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationInvitationListInvitations>()?,
                    resend: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationInvitationResend>()?,
                    revoke: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationInvitationRevoke>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationInvitationAcceptInvocationError {
    Domain(AcceptError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationInvitationGetInvitationInvocationError {
    Domain(GetInvitationError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationInvitationInviteInvocationError {
    Domain(InviteError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationInvitationListInvitationsInvocationError {
    Domain(ListInvitationsError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationInvitationResendInvocationError {
    Domain(ResendError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationInvitationRevokeInvocationError {
    Domain(RevokeError),
    Runtime(RuntimeFailure),
}
